package com.aglushkov.wordteacher.shared.model.label_map

import com.aglushkov.wordteacher.shared.model.WordTeacherWord


// from CollinsCobuildEnEn_abrv
val collinsCobuildLabelToPartOfSpeechMap = mapOf(
    "adj" to WordTeacherWord.PartOfSpeech.Adjective,
    "adj-compar" to WordTeacherWord.PartOfSpeech.Adjective,
    "adj-superl" to WordTeacherWord.PartOfSpeech.Adjective,
    "adj" to WordTeacherWord.PartOfSpeech.Adjective,
    "adv" to WordTeacherWord.PartOfSpeech.Adverb,
    "aux" to WordTeacherWord.PartOfSpeech.Verb,
    "conj" to WordTeacherWord.PartOfSpeech.Conjunction,
    "def-n" to WordTeacherWord.PartOfSpeech.Noun,
    "def-n-uncount" to WordTeacherWord.PartOfSpeech.Noun,
    "def-pl-n" to WordTeacherWord.PartOfSpeech.Noun,
    "det" to WordTeacherWord.PartOfSpeech.Determiner,
    "det-poss" to WordTeacherWord.PartOfSpeech.Determiner,
    "exclam" to WordTeacherWord.PartOfSpeech.Exclamation,
    "link" to WordTeacherWord.PartOfSpeech.Verb,
    "modal" to WordTeacherWord.PartOfSpeech.Verb,
    "n" to WordTeacherWord.PartOfSpeech.Noun,
    "n {(}not pron" to WordTeacherWord.PartOfSpeech.Noun,
    "n-count" to WordTeacherWord.PartOfSpeech.Noun,
    "v-count-coll" to WordTeacherWord.PartOfSpeech.Noun,
    "n-family" to WordTeacherWord.PartOfSpeech.Noun,
    "n-in-names" to WordTeacherWord.PartOfSpeech.Noun,
    "n-mass" to WordTeacherWord.PartOfSpeech.Noun,
    "n-plural" to WordTeacherWord.PartOfSpeech.Noun,
    "n-proper" to WordTeacherWord.PartOfSpeech.Noun,
    "n-proper-coll" to WordTeacherWord.PartOfSpeech.Noun,
    "n-proper-plural" to WordTeacherWord.PartOfSpeech.Noun,
    "n-sing-coll" to WordTeacherWord.PartOfSpeech.Noun,
    "n-sing" to WordTeacherWord.PartOfSpeech.Noun,
    "n-title" to WordTeacherWord.PartOfSpeech.Noun,
    "n-uncount" to WordTeacherWord.PartOfSpeech.Noun,
    "n-uncount-coll" to WordTeacherWord.PartOfSpeech.Noun,
    "n-uncount" to WordTeacherWord.PartOfSpeech.Noun,
    "n-var" to WordTeacherWord.PartOfSpeech.Noun,
    "n-var-coll" to WordTeacherWord.PartOfSpeech.Noun,
    "n-voc" to WordTeacherWord.PartOfSpeech.Noun,
    "passive" to WordTeacherWord.PartOfSpeech.Verb,
    "phrasal verb" to WordTeacherWord.PartOfSpeech.Verb,
    "pl-n" to WordTeacherWord.PartOfSpeech.Noun,
    "prep" to WordTeacherWord.PartOfSpeech.Preposition,
    "prep-phrase" to WordTeacherWord.PartOfSpeech.Preposition,
    "pron" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron-indef" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron-recip" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron-refl" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron-rel" to WordTeacherWord.PartOfSpeech.Pronoun,
    "recip" to WordTeacherWord.PartOfSpeech.Verb,
    "sing-n" to WordTeacherWord.PartOfSpeech.Noun,
    "v" to WordTeacherWord.PartOfSpeech.Verb,
    "v-cont" to WordTeacherWord.PartOfSpeech.Verb,
    "v-ed" to WordTeacherWord.PartOfSpeech.Verb,
    "v-ing" to WordTeacherWord.PartOfSpeech.Verb,
    "v-link" to WordTeacherWord.PartOfSpeech.Verb,
    "v-passive" to WordTeacherWord.PartOfSpeech.Verb,
    "v-recip" to WordTeacherWord.PartOfSpeech.Verb,
    "v-recip-passive" to WordTeacherWord.PartOfSpeech.Verb,
    "verb" to WordTeacherWord.PartOfSpeech.Verb,
)

val collinsCobuildLabelMap = mapOf(
    "brd-neg" to "broad negative",
    "cl" to "clause",
    "colour" to "colour",
    "comb" to "combining form",
    "compar" to "comparative form",
    "cont" to "continuous",
    "convention" to "convention",
    "fraction" to "fraction",
    "imper" to "imperative",
    "inf" to "infinitive",
    "names" to "pronoun names",
    "neg" to "negative",
    "non-recip" to "verb pattern with no reciprocal meaning",
    "num" to "number",
    "ord" to "ordinal",
    "p" to "particle, part of a phrasal verb",
    "passive" to "passive voice",
    "phrase" to "phrase",
    "pl" to "plural",
    "pl-num" to "plural number",
    "poss" to "possessive",
    "predet" to "predeterminer",
    "quant" to "quantifier",
    "quant-pl" to "plural quantifier",
    "quant-plural" to "plural quantifier",
    "quest" to "question word",
    "quote" to "direct speech",
    "sing" to "singular",
    "sound" to "sound word",
    "suffix" to "suffix",
    "sound" to "sound word",
    "supp" to "supplementary information",
    "that" to "'that'-clause",
    "to-inf" to "the to-infinitive form of a verb",
    "way" to "way preceded by a possessive",
    "wh" to "wh-word"
)