package com.aglushkov.wordteacher.shared.model.label_map

import com.aglushkov.wordteacher.shared.model.WordTeacherWord


// from CollinsCobuildEnEn_abrv
val collinsCobuildLabelToPartOfSpeechMap = mapOf(
    "adj" to WordTeacherWord.PartOfSpeech.Adjective,
    "adj-compar" to WordTeacherWord.PartOfSpeech.Adjective,
    "adj-superl" to WordTeacherWord.PartOfSpeech.Adjective,
    "ADJ." to WordTeacherWord.PartOfSpeech.Adjective,
    "ADJ:" to WordTeacherWord.PartOfSpeech.Adjective,
    "adv" to WordTeacherWord.PartOfSpeech.Adverb,
    "ADV." to WordTeacherWord.PartOfSpeech.Adverb,
    "ADV:" to WordTeacherWord.PartOfSpeech.Adverb,
    "AUX" to WordTeacherWord.PartOfSpeech.Verb,
    "AUX." to WordTeacherWord.PartOfSpeech.Verb,
    "AUX:" to WordTeacherWord.PartOfSpeech.Verb,
    "CONJ" to WordTeacherWord.PartOfSpeech.Conjunction,
    "CONJ." to WordTeacherWord.PartOfSpeech.Conjunction,
    "CONJ:" to WordTeacherWord.PartOfSpeech.Conjunction,
    "def-n" to WordTeacherWord.PartOfSpeech.Noun,
    "def-n-uncount" to WordTeacherWord.PartOfSpeech.Noun,
    "def-pl-n" to WordTeacherWord.PartOfSpeech.Noun,
    "det" to WordTeacherWord.PartOfSpeech.Determiner,
    "det-poss" to WordTeacherWord.PartOfSpeech.Determiner,
    "EXCLAM" to WordTeacherWord.PartOfSpeech.Exclamation,
    "EXCLAM." to WordTeacherWord.PartOfSpeech.Exclamation,
    "EXCLAM:" to WordTeacherWord.PartOfSpeech.Exclamation,
    "LINK" to WordTeacherWord.PartOfSpeech.Verb,
    "LINK." to WordTeacherWord.PartOfSpeech.Verb,
    "LINK:" to WordTeacherWord.PartOfSpeech.Verb,
    "MODAL" to WordTeacherWord.PartOfSpeech.Verb,
    "MODAL." to WordTeacherWord.PartOfSpeech.Verb,
    "MODAL:" to WordTeacherWord.PartOfSpeech.Verb,
    "n" to WordTeacherWord.PartOfSpeech.Noun,
    "n {(}not pron{)}" to WordTeacherWord.PartOfSpeech.Noun,
    "N-COUNT" to WordTeacherWord.PartOfSpeech.Noun,
    "N-COUNT-COLL" to WordTeacherWord.PartOfSpeech.Noun,
    "N-COUNT-COLL." to WordTeacherWord.PartOfSpeech.Noun,
    "N-COUNT-COLL:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-COUNT." to WordTeacherWord.PartOfSpeech.Noun,
    "N-COUNT:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-FAMILY" to WordTeacherWord.PartOfSpeech.Noun,
    "N-FAMILY." to WordTeacherWord.PartOfSpeech.Noun,
    "N-FAMILY:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-IN-NAMES" to WordTeacherWord.PartOfSpeech.Noun,
    "N-IN-NAMES." to WordTeacherWord.PartOfSpeech.Noun,
    "N-IN-NAMES:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-MASS" to WordTeacherWord.PartOfSpeech.Noun,
    "N-MASS." to WordTeacherWord.PartOfSpeech.Noun,
    "N-MASS:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-PLURAL" to WordTeacherWord.PartOfSpeech.Noun,
    "N-PLURAL." to WordTeacherWord.PartOfSpeech.Noun,
    "N-PLURAL:" to WordTeacherWord.PartOfSpeech.Noun,
    "n-proper" to WordTeacherWord.PartOfSpeech.Noun,
    "N-PROPER-COLL" to WordTeacherWord.PartOfSpeech.Noun,
    "N-PROPER-COLL." to WordTeacherWord.PartOfSpeech.Noun,
    "N-PROPER-COLL:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-PROPER-PLURAL" to WordTeacherWord.PartOfSpeech.Noun,
    "N-PROPER-PLURAL." to WordTeacherWord.PartOfSpeech.Noun,
    "N-PROPER-PLURAL:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-SING" to WordTeacherWord.PartOfSpeech.Noun,
    "N-SING-COLL" to WordTeacherWord.PartOfSpeech.Noun,
    "N-SING-COLL." to WordTeacherWord.PartOfSpeech.Noun,
    "N-SING-COLL:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-SING." to WordTeacherWord.PartOfSpeech.Noun,
    "N-SING:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-TITLE" to WordTeacherWord.PartOfSpeech.Noun,
    "N-TITLE." to WordTeacherWord.PartOfSpeech.Noun,
    "N-TITLE:" to WordTeacherWord.PartOfSpeech.Noun,
    "n-uncount" to WordTeacherWord.PartOfSpeech.Noun,
    "N-UNCOUNT-COLL" to WordTeacherWord.PartOfSpeech.Noun,
    "N-UNCOUNT-COLL." to WordTeacherWord.PartOfSpeech.Noun,
    "N-UNCOUNT-COLL:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-UNCOUNT." to WordTeacherWord.PartOfSpeech.Noun,
    "N-UNCOUNT:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-VAR" to WordTeacherWord.PartOfSpeech.Noun,
    "N-VAR-COLL" to WordTeacherWord.PartOfSpeech.Noun,
    "N-VAR-COLL." to WordTeacherWord.PartOfSpeech.Noun,
    "N-VAR-COLL:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-VAR." to WordTeacherWord.PartOfSpeech.Noun,
    "N-VAR:" to WordTeacherWord.PartOfSpeech.Noun,
    "N-VOC" to WordTeacherWord.PartOfSpeech.Noun,
    "N-VOC." to WordTeacherWord.PartOfSpeech.Noun,
    "N-VOC:" to WordTeacherWord.PartOfSpeech.Noun,
    "PASSIVE." to WordTeacherWord.PartOfSpeech.Verb,
    "PASSIVE:" to WordTeacherWord.PartOfSpeech.Verb,
    "PHRASAL VERB" to WordTeacherWord.PartOfSpeech.Verb,
    "PHRASAL VERB." to WordTeacherWord.PartOfSpeech.Verb,
    "PHRASAL VERB:" to WordTeacherWord.PartOfSpeech.Verb,
    "pl-n" to WordTeacherWord.PartOfSpeech.Noun,
    "prep" to WordTeacherWord.PartOfSpeech.Preposition,
    "PREP-PHRASE" to WordTeacherWord.PartOfSpeech.Preposition,
    "PREP-PHRASE." to WordTeacherWord.PartOfSpeech.Preposition,
    "PREP-PHRASE:" to WordTeacherWord.PartOfSpeech.Preposition,
    "PREP." to WordTeacherWord.PartOfSpeech.Preposition,
    "PREP:" to WordTeacherWord.PartOfSpeech.Preposition,
    "pron" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron-indef" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron-recip" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron-refl" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron-rel" to WordTeacherWord.PartOfSpeech.Pronoun,
    "PRON." to WordTeacherWord.PartOfSpeech.Pronoun,
    "PRON:" to WordTeacherWord.PartOfSpeech.Pronoun,
    "RECIP" to WordTeacherWord.PartOfSpeech.Verb,
    "RECIP." to WordTeacherWord.PartOfSpeech.Verb,
    "RECIP:" to WordTeacherWord.PartOfSpeech.Verb,
    "sing-n" to WordTeacherWord.PartOfSpeech.Noun,
    "v" to WordTeacherWord.PartOfSpeech.Verb,
    "v-cont" to WordTeacherWord.PartOfSpeech.Verb,
    "V-ed" to WordTeacherWord.PartOfSpeech.Verb,
    "V-ed:" to WordTeacherWord.PartOfSpeech.Verb,
    "V-ing" to WordTeacherWord.PartOfSpeech.Verb,
    "V-ing." to WordTeacherWord.PartOfSpeech.Verb,
    "V-ing:" to WordTeacherWord.PartOfSpeech.Verb,
    "v-link" to WordTeacherWord.PartOfSpeech.Verb,
    "V-PASSIVE" to WordTeacherWord.PartOfSpeech.Verb,
    "V-PASSIVE." to WordTeacherWord.PartOfSpeech.Verb,
    "V-PASSIVE:" to WordTeacherWord.PartOfSpeech.Verb,
    "V-RECIP" to WordTeacherWord.PartOfSpeech.Verb,
    "V-RECIP-PASSIVE" to WordTeacherWord.PartOfSpeech.Verb,
    "V-RECIP-PASSIVE." to WordTeacherWord.PartOfSpeech.Verb,
    "V-RECIP-PASSIVE:" to WordTeacherWord.PartOfSpeech.Verb,
    "V-RECIP." to WordTeacherWord.PartOfSpeech.Verb,
    "V-RECIP:" to WordTeacherWord.PartOfSpeech.Verb,
    "VERB" to WordTeacherWord.PartOfSpeech.Verb,
    "VERB." to WordTeacherWord.PartOfSpeech.Verb,
    "VERB:" to WordTeacherWord.PartOfSpeech.Verb,
)

val collinsCobuildLabelMap = mapOf(
    "brd-neg" to "broad negative",
    "cl" to "clause",
    "COLOUR." to "colour",
    "COLOUR:" to "colour",
    "COMB" to "combining form",
    "COMB." to "combining form",
    "COMB:" to "combining form",
    "compar" to "comparative form",
    "cont" to "continuous",
    "CONVENTION" to "convention",
    "CONVENTION." to "convention",
    "CONVENTION:" to "convention",
    "FRACTION" to "fraction",
    "FRACTION." to "fraction",
    "FRACTION:" to "fraction",
    "imper" to "imperative",
    "inf" to "infinitive",
    "names" to "pronoun names",
    "neg" to "negative",
    "non-recip" to "verb pattern with no reciprocal meaning",
    "num" to "number",
    "NUM." to "number",
    "NUM:" to "number",
    "ord" to "ordinal",
    "ORD." to "ordinal",
    "ORD:" to "ordinal",
    "P" to "particle, part of a phrasal verb",
    "P." to "particle, part of a phrasal verb",
    "P:" to "particle, part of a phrasal verb",
    "passive" to "passive voice",
    "PHRASE" to "phrase",
    "PHRASE." to "phrase",
    "PHRASE:" to "phrase",
    "pl" to "plural",
    "pl-num" to "plural number",
    "poss" to "possessive",
    "PREDET" to "predeterminer",
    "PREDET." to "predeterminer",
    "PREDET:" to "predeterminer",
    "PREFIX" to "prefix",
    "PREFIX." to "prefix",
    "PREFIX:" to "prefix",
    "QUANT" to "quantifier",
    "QUANT-PL." to "plural quantifier",
    "QUANT-PLURAL" to "plural quantifier",
    "QUANT-PLURAL:" to "plural quantifier",
    "QUANT." to "quantifier",
    "QUANT:" to "quantifier",
    "quest" to "question word",
    "QUEST." to "question word",
    "QUEST:" to "question word",
    "quote" to "direct speech",
    "sing" to "singular",
    "SOUND" to "sound word",
    "SOUND." to "sound word",
    "SOUND:" to "sound word",
    "SUFFIX" to "suffix",
    "SUFFIX." to "suffix",
    "SUFFIX:" to "suffix",
    "supp" to "supplementary information",
    "that" to "'that'-clause",
    "to-inf" to "the to-infinitive form of a verb",
    "way" to "way preceded by a possessive",
    "wh" to "wh-word",
    "♦" to "low frequency",
    "♦♦" to "normal frequency",
    "♦♦♦" to "high frequency",
)