package com.aglushkov.wordteacher.shared.model.label_map

import com.aglushkov.wordteacher.shared.model.WordTeacherWord

// https://en.wiktionary.org/wiki/User:Matthias_Buchmeier/tagset
// https://github.com/open-dsl-dict/wiktionary-dict
val matthiasBuchmeierLabelToPartOfSpeechMap = mapOf(
    "<noun>" to WordTeacherWord.PartOfSpeech.Noun,
    "<n>" to WordTeacherWord.PartOfSpeech.Noun,
    "<v>" to WordTeacherWord.PartOfSpeech.Verb,
    "<vi>" to WordTeacherWord.PartOfSpeech.Verb,
    "<vt>" to WordTeacherWord.PartOfSpeech.Verb,
    "<vr>" to WordTeacherWord.PartOfSpeech.Verb,
    "<vp>" to WordTeacherWord.PartOfSpeech.Verb,
    "<vit>" to WordTeacherWord.PartOfSpeech.Verb,
    "<vti>" to WordTeacherWord.PartOfSpeech.Verb,
    "<v pf>" to WordTeacherWord.PartOfSpeech.Verb,
    "<v impf>" to WordTeacherWord.PartOfSpeech.Verb,
    "<adj>" to WordTeacherWord.PartOfSpeech.Adjective,
    "<adv>" to WordTeacherWord.PartOfSpeech.Adverb,
    "<prop>" to WordTeacherWord.PartOfSpeech.Noun,
    "<interj>" to WordTeacherWord.PartOfSpeech.Interjection,
    "<prep>" to WordTeacherWord.PartOfSpeech.Preposition,
    "<pron>" to WordTeacherWord.PartOfSpeech.Pronoun,
    "<conj>" to WordTeacherWord.PartOfSpeech.Conjunction,
    "<abbr>" to WordTeacherWord.PartOfSpeech.Abbreviation,
    "<determiner>" to WordTeacherWord.PartOfSpeech.Determiner,
    "<determiner>" to WordTeacherWord.PartOfSpeech.Determiner,
)

val matthiasBuchmeierLabelMap = mapOf(
    "<art>" to "article",
    "<article>" to "article",
    "<pred>" to "predicate",
    "<phrase>" to "phrase",
    "<proverb>" to "proverb",
    "<postp>" to "postposition",
    "<circump>" to "circumposition",
    "<ambip>" to "ambiposition",
    "<initialism>" to "initialism",
    "<acronym>" to "acronym",
    "<symbol>" to "symbol",
    "<letter>" to "letter",
    "<han>" to "han character",
    "<num>" to "numeral",
    "<punct>" to "punctuation mark",
    "<diacrit>" to "diacritical mark",
    "<particle>" to "particle",
    "<classifier>" to "classifier",
    "<contraction>" to "contraction",
    "<prefix>" to "prefix",
    "<suffix>" to "suffix",
    "<interfix>" to "interfix",
    "<affix>" to "affix",
    "<circumfix>" to "circumfix",
    "<clitic>" to "clitic",
    "<unk>" to "word",
    "<idiom>" to "idiom",
    "<anim>" to "animate",
    "<inan>" to "inanimate",
    "<m anim>" to "masculine animate",
    "<f anim>" to "feminine animate",
    "<s>" to "singular",
    "<p>" to "plural",
    "<mp>" to "masculine plural",
    "<m-p>" to "masculine plural",
    "<fp>" to "feminine plural",
    "<f-p>" to "feminine plural",
    "<m>" to "masculine",
    "<f>" to "feminine",
    "<n>" to "neuter",
    "<c>" to "common",
    "<mf>" to "masculine or feminine",
    "<m-f>" to "masculine or feminine",
)
