package com.aglushkov.wordteacher.shared.model.label_map

import com.aglushkov.wordteacher.shared.model.WordTeacherWord

val ruLabelToPartOfSpeech = mapOf(
    "noun" to WordTeacherWord.PartOfSpeech.Noun,
    "v" to WordTeacherWord.PartOfSpeech.Verb,
    "v aux" to WordTeacherWord.PartOfSpeech.Verb,
    "v impers" to WordTeacherWord.PartOfSpeech.Verb,
    "vi" to WordTeacherWord.PartOfSpeech.Verb,
    "vimp" to WordTeacherWord.PartOfSpeech.Verb,
    "vt" to WordTeacherWord.PartOfSpeech.Verb,
    "adj" to WordTeacherWord.PartOfSpeech.Adjective,
    "adj." to WordTeacherWord.PartOfSpeech.Adjective,
    "adv" to WordTeacherWord.PartOfSpeech.Adverb,
    "adv." to WordTeacherWord.PartOfSpeech.Adverb,
    "pron dem" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron imp" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron indef" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron inter" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron pers" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron poss" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron refl" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron rel" to WordTeacherWord.PartOfSpeech.Pronoun,
    "prep" to WordTeacherWord.PartOfSpeech.Preposition,
    "prép" to WordTeacherWord.PartOfSpeech.Preposition,
    "präp" to WordTeacherWord.PartOfSpeech.Preposition,
    "conj" to WordTeacherWord.PartOfSpeech.Conjunction,
    "int" to WordTeacherWord.PartOfSpeech.Interjection,
    "interj" to WordTeacherWord.PartOfSpeech.Interjection,

    "сущ" to WordTeacherWord.PartOfSpeech.Noun,
    "сущ." to WordTeacherWord.PartOfSpeech.Noun,
    "безл." to WordTeacherWord.PartOfSpeech.Verb,
    "вз.-возвр." to WordTeacherWord.PartOfSpeech.Verb,
    "возвр." to WordTeacherWord.PartOfSpeech.Verb,
    "гл." to WordTeacherWord.PartOfSpeech.Verb,
    "глаг." to WordTeacherWord.PartOfSpeech.Verb,
    "модал." to WordTeacherWord.PartOfSpeech.Verb,
    "направл." to WordTeacherWord.PartOfSpeech.Verb,
    "ненаправл." to WordTeacherWord.PartOfSpeech.Verb,
    "непер." to WordTeacherWord.PartOfSpeech.Verb,
    "неперех." to WordTeacherWord.PartOfSpeech.Verb,
    "несовер." to WordTeacherWord.PartOfSpeech.Verb,
    "прил" to WordTeacherWord.PartOfSpeech.Adjective,
    "прил." to WordTeacherWord.PartOfSpeech.Adjective,
    "нареч" to WordTeacherWord.PartOfSpeech.Adverb,
    "нареч." to WordTeacherWord.PartOfSpeech.Adverb,
    "составное наречие" to WordTeacherWord.PartOfSpeech.Adverb,
    "взаимн." to WordTeacherWord.PartOfSpeech.Pronoun,
    "вопр." to WordTeacherWord.PartOfSpeech.Pronoun,
    "лич." to WordTeacherWord.PartOfSpeech.Pronoun,
    "личн." to WordTeacherWord.PartOfSpeech.Pronoun,
    "отн." to WordTeacherWord.PartOfSpeech.Pronoun,
    "относ." to WordTeacherWord.PartOfSpeech.Pronoun,
    "относит." to WordTeacherWord.PartOfSpeech.Pronoun,
    "притяж." to WordTeacherWord.PartOfSpeech.Pronoun,
    "мест" to WordTeacherWord.PartOfSpeech.Pronoun,
    "мест." to WordTeacherWord.PartOfSpeech.Pronoun,
    "предл." to WordTeacherWord.PartOfSpeech.Preposition,
    "сост. пред." to WordTeacherWord.PartOfSpeech.Preposition,
    "парн. союз" to WordTeacherWord.PartOfSpeech.Conjunction,
    "сост. союз" to WordTeacherWord.PartOfSpeech.Conjunction,
    "союз" to WordTeacherWord.PartOfSpeech.Conjunction,
    "сравнит." to WordTeacherWord.PartOfSpeech.Conjunction,
    "межд" to WordTeacherWord.PartOfSpeech.Interjection,
    "межд." to WordTeacherWord.PartOfSpeech.Interjection,
    "аббр." to WordTeacherWord.PartOfSpeech.Abbreviation,
    "воскл." to WordTeacherWord.PartOfSpeech.Exclamation,
    "фраз. гл" to WordTeacherWord.PartOfSpeech.PhrasalVerb,
    "фраз. гл." to WordTeacherWord.PartOfSpeech.PhrasalVerb,
)

val ruLabelMap = mapOf(
    "A" to "винительный падеж"
)
