package com.aglushkov.wordteacher.shared.model.label_map

import com.aglushkov.wordteacher.shared.model.WordTeacherWord

val ruLabelToPartOfSpeech = mapOf(
    "noun" to WordTeacherWord.PartOfSpeech.Noun,
    "v" to WordTeacherWord.PartOfSpeech.Verb,
    "v aux" to WordTeacherWord.PartOfSpeech.Verb,
    "v impers" to WordTeacherWord.PartOfSpeech.Verb,
    "vi" to WordTeacherWord.PartOfSpeech.Verb,
    "vimp" to WordTeacherWord.PartOfSpeech.Verb,
    "vt" to WordTeacherWord.PartOfSpeech.Verb,
    "adj" to WordTeacherWord.PartOfSpeech.Adjective,
    "adv" to WordTeacherWord.PartOfSpeech.Adverb,
    "pron dem" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron imp" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron indef" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron inter" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron pers" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron poss" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron refl" to WordTeacherWord.PartOfSpeech.Pronoun,
    "pron rel" to WordTeacherWord.PartOfSpeech.Pronoun,
    "prep" to WordTeacherWord.PartOfSpeech.Preposition,
    "prép" to WordTeacherWord.PartOfSpeech.Preposition,
    "präp" to WordTeacherWord.PartOfSpeech.Preposition,
    "conj" to WordTeacherWord.PartOfSpeech.Conjunction,
    "int" to WordTeacherWord.PartOfSpeech.Interjection,
    "interj" to WordTeacherWord.PartOfSpeech.Interjection,

    "сущ" to WordTeacherWord.PartOfSpeech.Noun,
    "безл" to WordTeacherWord.PartOfSpeech.Verb,
    "вз.-возвр" to WordTeacherWord.PartOfSpeech.Verb,
    "возвр" to WordTeacherWord.PartOfSpeech.Verb,
    "гл" to WordTeacherWord.PartOfSpeech.Verb,
    "глаг" to WordTeacherWord.PartOfSpeech.Verb,
    "модал" to WordTeacherWord.PartOfSpeech.Verb,
    "направл" to WordTeacherWord.PartOfSpeech.Verb,
    "ненаправл" to WordTeacherWord.PartOfSpeech.Verb,
    "непер" to WordTeacherWord.PartOfSpeech.Verb,
    "неперех" to WordTeacherWord.PartOfSpeech.Verb,
    "несовер" to WordTeacherWord.PartOfSpeech.Verb,
    "прил" to WordTeacherWord.PartOfSpeech.Adjective,
    "нареч" to WordTeacherWord.PartOfSpeech.Adverb,
    "составное наречие" to WordTeacherWord.PartOfSpeech.Adverb,
    "взаимн" to WordTeacherWord.PartOfSpeech.Pronoun,
    "вопр" to WordTeacherWord.PartOfSpeech.Pronoun,
    "лич" to WordTeacherWord.PartOfSpeech.Pronoun,
    "личн" to WordTeacherWord.PartOfSpeech.Pronoun,
    "отн" to WordTeacherWord.PartOfSpeech.Pronoun,
    "относ" to WordTeacherWord.PartOfSpeech.Pronoun,
    "относит" to WordTeacherWord.PartOfSpeech.Pronoun,
    "притяж" to WordTeacherWord.PartOfSpeech.Pronoun,
    "мест" to WordTeacherWord.PartOfSpeech.Pronoun,
    "предл" to WordTeacherWord.PartOfSpeech.Preposition,
    "сост. пред" to WordTeacherWord.PartOfSpeech.Preposition,
    "парн. союз" to WordTeacherWord.PartOfSpeech.Conjunction,
    "сост. союз" to WordTeacherWord.PartOfSpeech.Conjunction,
    "союз" to WordTeacherWord.PartOfSpeech.Conjunction,
    "сравнит" to WordTeacherWord.PartOfSpeech.Conjunction,
    "межд" to WordTeacherWord.PartOfSpeech.Interjection,
    "аббр" to WordTeacherWord.PartOfSpeech.Abbreviation,
    "воскл" to WordTeacherWord.PartOfSpeech.Exclamation,
    "фраз. гл" to WordTeacherWord.PartOfSpeech.PhrasalVerb,
)

val ruLabelMap = mapOf(
    "A" to "винительный падеж",
    "%%" to "цитируемая подстатья",
    "аббр" to "аббревиатура",
    "авиа" to "авиация",
    "австрал" to "употребляется в Австралии",
    "авто" to "автомобильное дело",
    "амер" to "американский вариант английского языка; употребляется в США",
    "анат" to "анатомия",
    "араб" to "арабский язык",
    "археол" to "археология",
    "архит" to "архитектура",
    "астр" to "астрономия",
    "астрол" to "астрология",
    "афр" to "африканские языки",
    "африкаанс" to "африкаанс",
    "библ" to "библейское",
    "биол" to "биология",
    "бирж" to "биржевое дело",
    "бот" to "ботаника",
    "брит" to "британский вариант английского языка; употребляется в Великобритании",
    "букв" to "буквально",
    "венг" to "венгерский язык",
    "вет" to "ветеринария",
    "воен" to "военное дело",
    "высок" to "высокое",
    "гавайск" to "гавайский язык",
    "геогр" to "география",
    "геол" to "геология",
    "геральд" to "геральдика",
    "гидр" to "гидрология и гидротехника",
    "гл" to "глагол",
    "голл" to "голландский язык",
    "горн" to "горное дело",
    "греч" to "греческий язык (разных периодов)",
    "груб" to "грубое",
    "детск" to "детское",
    "диал" to "диалектное",
    "дип" to "дипломатия",
    "дор" to "дорожное дело",
    "ед" to "единственное число",
    "ж.-д" to "железнодорожное дело",
    "жарг" to "жаргонное",
    "журн" to "журналистика и СМИ",
    "звукоподр" to "звукоподражательное",
    "зоол" to "зоология",
    "иврит" to "иврит (разных периодов)",
    "идиом" to "идиоматическое",
    "идиш" to "идиш",
    "инд" to "индийские языки",
    "инф" to "инфинитив",
    "информ" to "информатика и компьютерные технологии",
    "ирл" to "ирландский язык",
    "ирон" to "ироническое",
    "иск" to "искусство",
    "искаж" to "искаженное",
    "исп" to "испанский язык",
    "ист" to "история; историческое",
    "итал" to "итальянский язык",
    "канад" to "употребляется в Канаде",
    "карт" to "карточные игры",
    "кино" to "кинематография",
    "кит" to "китайский язык",
    "книжн" to "литературно-книжное",
    "ком" to "коммерция",
    "косм" to "космонавтика и ракетостроение",
    "крим" to "криминальный жаргон",
    "кул" to "кулинария",
    "л" to "(грамматическое) лицо",
    "ласк" to "ласкательное",
    "лат" to "латинский язык",
    "лес" to "лесное дело",
    "лингв" to "лингвистика",
    "лит" to "литературоведение",
    "лог" to "логика",
    "марк" to "маркетинг и реклама",
    "мат" to "математика",
    "мед" to "медицина",
    "межд" to "междометие (часть речи)",
    "мест" to "местоимение",
    "метал" to "металлургия и металлообработка",
    "метео" to "метеорология",
    "миф" to "мифология",
    "мн" to "множественное число",
    "мор" to "морское дело",
    "муз" to "музыка",
    "нареч" to "наречие",
    "нарк" to "жаргон наркоманов",
    "не употр. атриб" to "не употребляется атрибутивно",
    "неисч" to "неисчисляемое",
    "нем" to "немецкий язык",
    "неодобр" to "неодобрительное",
    "нефт" to "нефтегазовое дело",
    "неценз" to "нецензурное",
    "новозел" to "употребляется в Новой Зеландии",
    "норв" to "норвежский язык",
    "охот" to "охотничий термин",
    "палеонт" to "палеонтология",
    "перс" to "персидский язык",
    "полигр" to "полиграфическое и издательское дело",
    "полит" to "политика",
    "политкор" to "политкорректное",
    "польск" to "польский язык",
    "португ" to "португальский язык",
    "посл" to "пословица",
    "поэт" to "поэтическое",
    "превосх. ст" to "превосходная степень прилагательного или наречия",
    "предик" to "предикатив",
    "предл" to "предлог",
    "презр" to "презрительное",
    "преим" to "преимущественно",
    "пренебр" to "пренебрежительное",
    "прил" to "имя прилагательное",
    "прист" to "приставка, префиксоид, первая часть сложных слов",
    "притяж. мест" to "притяжательное местоимение",
    "прич" to "причастие",
    "прич. наст. вр" to "причастие настоящего времени",
    "прич. прош. вр" to "причастие прошедшего времени",
    "прост" to "просторечное, не вполне грамотное",
    "прош. вр" to "прошедшее время",
    "прям. и перен" to "в прямом и переносном значении",
    "психол" to "психология",
    "радио" to "радиодело; радиовещание",
    "разг" to "разговорное",
    "редк" to "редкое",
    "рел" to "религия и религиозные культы",
    "русск" to "русский язык",
    "рыб" to "рыболовство и рыбоводство",
    "с.-х" to "сельское хозяйство",
    "сканд" to "скандинавские языки",
    "см. тж" to "смотри также",
    "сниж" to "сниженное",
    "сокр" to "сокращение",
    "социол" to "социология",
    "союз" to "союз (часть речи)",
    "спорт" to "спорт",
    "ср" to "сравните",
    "сравн. ст" to "сравнительная степень прилагательных или наречий",
    "стат" to "статистика",
    "стр" to "строительное дело",
    "страд" to "страдательный залог",
    "страх" to "страховое дело",
    "студ" to "студенческий или школьный жаргон",
    "суф" to "суффикс, cуффиксоид, вторая часть сложных слов",
    "сущ" to "имя существительное",
    "театр" to "театральное дело",
    "текст" to "текстильное дело",
    "тех" to "технический термин",
    "тж" to "также",
    "тлв" to "телевидение",
    "тур" to "турецкий язык",
    "уменьш" to "уменьшительное",
    "употр. с гл. в ед" to "употребляется с глаголами в единственном числе",
    "употр. с гл. в ед. и мн" to "употребляется с глаголами в единственном и множественном числе",
    "употр. с гл. во мн" to "употребляется с глаголами во множественном числе",
    "уст" to "устаревшее",
    "фарм" to "фармацевтика и фармакология",
    "физ" to "физика",
    "физиол" to "физиология",
    "филос" to "философия",
    "фин" to "финансовое дело и бухгалтерское дело",
    "фото" to "фотодело",
    "фр" to "французский язык",
    "фраз. гл" to "фразовый глагол",
    "хим" to "химия и химические технологии",
    "числ" to "имя числительное",
    "шахм" to "шахматы",
    "шотл" to "употребляется в Шотландии",
    "шутл" to "шутливое",
    "эвф" to "эвфемистическое",
    "эк" to "экономика",
    "экол" to "экология",
    "эл" to "электротехника",
    "юр" to "юриспруденция",
    "япон" to "японский язык",
)
