//
//// required tools
//$ go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
//$ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
//
//// generate source
//protoc --go_out=service_articles/pkg/grpc --go_opt=paths=source_relative \
//--go-grpc_out=service_articles/pkg/grpc --go-grpc_opt=paths=source_relative \
//service_articles/api/headlines.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.2
// source: service_articles/api/headlines.proto

package articlesgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_ALL  Category = 0
	Category_NEWS Category = 1
	Category_TECH Category = 2
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "ALL",
		1: "NEWS",
		2: "TECH",
	}
	Category_value = map[string]int32{
		"ALL":  0,
		"NEWS": 1,
		"TECH": 2,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_service_articles_api_headlines_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_service_articles_api_headlines_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_service_articles_api_headlines_proto_rawDescGZIP(), []int{0}
}

type GetHeadlinesIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      Category               `protobuf:"varint,1,opt,name=category,proto3,enum=articlesgrpc.Category" json:"category,omitempty"`
	Limit         *int64                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Since         *string                `protobuf:"bytes,3,opt,name=since,proto3,oneof" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadlinesIn) Reset() {
	*x = GetHeadlinesIn{}
	mi := &file_service_articles_api_headlines_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadlinesIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadlinesIn) ProtoMessage() {}

func (x *GetHeadlinesIn) ProtoReflect() protoreflect.Message {
	mi := &file_service_articles_api_headlines_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadlinesIn.ProtoReflect.Descriptor instead.
func (*GetHeadlinesIn) Descriptor() ([]byte, []int) {
	return file_service_articles_api_headlines_proto_rawDescGZIP(), []int{0}
}

func (x *GetHeadlinesIn) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_ALL
}

func (x *GetHeadlinesIn) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetHeadlinesIn) GetSince() string {
	if x != nil && x.Since != nil {
		return *x.Since
	}
	return ""
}

type Headline struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId       string                 `protobuf:"bytes,2,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	SourceName     string                 `protobuf:"bytes,3,opt,name=sourceName,proto3" json:"sourceName,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Link           string                 `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	Date           string                 `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Creator        *string                `protobuf:"bytes,8,opt,name=creator,proto3,oneof" json:"creator,omitempty"`
	SourceCategory string                 `protobuf:"bytes,9,opt,name=sourceCategory,proto3" json:"sourceCategory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Headline) Reset() {
	*x = Headline{}
	mi := &file_service_articles_api_headlines_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Headline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Headline) ProtoMessage() {}

func (x *Headline) ProtoReflect() protoreflect.Message {
	mi := &file_service_articles_api_headlines_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Headline.ProtoReflect.Descriptor instead.
func (*Headline) Descriptor() ([]byte, []int) {
	return file_service_articles_api_headlines_proto_rawDescGZIP(), []int{1}
}

func (x *Headline) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Headline) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Headline) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Headline) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Headline) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Headline) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Headline) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Headline) GetCreator() string {
	if x != nil && x.Creator != nil {
		return *x.Creator
	}
	return ""
}

func (x *Headline) GetSourceCategory() string {
	if x != nil {
		return x.SourceCategory
	}
	return ""
}

var File_service_articles_api_headlines_proto protoreflect.FileDescriptor

var file_service_articles_api_headlines_proto_rawDesc = string([]byte{
	0x0a, 0x24, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x67, 0x72, 0x70, 0x63, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x32, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x73, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x73, 0x69, 0x6e, 0x63, 0x65, 0x22, 0x89, 0x02, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x64, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a,
	0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x2a, 0x27, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x45, 0x57, 0x53, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x43, 0x48, 0x10, 0x02, 0x32, 0x55, 0x0a, 0x09, 0x48, 0x65,
	0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x48, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x48, 0x65,
	0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x73, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x49, 0x6e, 0x1a, 0x16, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x61, 0x67, 0x6c, 0x75, 0x73, 0x68, 0x6b, 0x6f, 0x76, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_service_articles_api_headlines_proto_rawDescOnce sync.Once
	file_service_articles_api_headlines_proto_rawDescData []byte
)

func file_service_articles_api_headlines_proto_rawDescGZIP() []byte {
	file_service_articles_api_headlines_proto_rawDescOnce.Do(func() {
		file_service_articles_api_headlines_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_articles_api_headlines_proto_rawDesc), len(file_service_articles_api_headlines_proto_rawDesc)))
	})
	return file_service_articles_api_headlines_proto_rawDescData
}

var file_service_articles_api_headlines_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_articles_api_headlines_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_articles_api_headlines_proto_goTypes = []any{
	(Category)(0),          // 0: articlesgrpc.Category
	(*GetHeadlinesIn)(nil), // 1: articlesgrpc.GetHeadlinesIn
	(*Headline)(nil),       // 2: articlesgrpc.Headline
}
var file_service_articles_api_headlines_proto_depIdxs = []int32{
	0, // 0: articlesgrpc.GetHeadlinesIn.category:type_name -> articlesgrpc.Category
	1, // 1: articlesgrpc.Headlines.GetHeadlines:input_type -> articlesgrpc.GetHeadlinesIn
	2, // 2: articlesgrpc.Headlines.GetHeadlines:output_type -> articlesgrpc.Headline
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_articles_api_headlines_proto_init() }
func file_service_articles_api_headlines_proto_init() {
	if File_service_articles_api_headlines_proto != nil {
		return
	}
	file_service_articles_api_headlines_proto_msgTypes[0].OneofWrappers = []any{}
	file_service_articles_api_headlines_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_articles_api_headlines_proto_rawDesc), len(file_service_articles_api_headlines_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_articles_api_headlines_proto_goTypes,
		DependencyIndexes: file_service_articles_api_headlines_proto_depIdxs,
		EnumInfos:         file_service_articles_api_headlines_proto_enumTypes,
		MessageInfos:      file_service_articles_api_headlines_proto_msgTypes,
	}.Build()
	File_service_articles_api_headlines_proto = out.File
	file_service_articles_api_headlines_proto_goTypes = nil
	file_service_articles_api_headlines_proto_depIdxs = nil
}
