server:
  http_listen_port: ${PROMTAIL_PORT}
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      service_name: nginx
      __path__: /var/log/nginx/*
  pipeline_stages:
  - json:
      expressions:
        time: time
        status:
        request_uri:
  - labels:
      request_uri:
      status:
  - timestamp:
      source: time
      format: RFC3339

- job_name: root
  static_configs:
  - targets:
      - localhost
    labels:
      service_name: root
      __path__: /var/log/root/*log

- job_name: service_auth
  static_configs:
  - targets:
      - localhost
    labels:
      service_name: service_auth
      __path__: /var/log/auth/service*
  pipeline_stages:
  - json:
      expressions:
        time:
        level:
        networkType:
        deviceType:
  - labels:
      level:
      networkType:
      deviceType:
  - timestamp:
      source: time
      format: RFC3339Nano

- job_name: service_cardsets
  static_configs:
  - targets:
      - localhost
    labels:
      service_name: service_cardsets
      __path__: /var/log/cardsets/service*
  pipeline_stages:
  - json:
      expressions:
        time:
        level:
        networkType:
        deviceType:
        userId:
  - labels:
      level:
      networkType:
      deviceType:
      userId:
  - timestamp:
      source: time
      format: RFC3339Nano

  - job_name: service_cardsetsearch
    static_configs:
    - targets:
        - localhost
      labels:
        service_name: service_cardsetsearch
        __path__: /var/log/cardsetsearch/service*
    pipeline_stages:
    - json:
        expressions:
          time:
          level:
          networkType:
          deviceType:
          userId:
    - labels:
        level:
        networkType:
        deviceType:
        userId:
    - timestamp:
        source: time
        format: RFC3339Nano

  - job_name: service_dict
    static_configs:
    - targets:
        - localhost
      labels:
        service_name: service_dict
        __path__: /var/log/dict/service*
    pipeline_stages:
    - json:
        expressions:
          time:
          level:
          networkType:
          deviceType:
          userId:
    - labels:
        level:
        networkType:
        deviceType:
        userId:
    - timestamp:
        source: time
        format: RFC3339Nano