server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /var/log/nginx/*
  pipeline_stages:
  - json:
      expressions:
        time: time
        request_uri: request_uri
  - labels:
      request_uri:
  - timestamp:
      source: time
      format: RFC3339
- job_name: root
  static_configs:
  - targets:
      - localhost
    labels:
      job: rootlogs
      __path__: /var/log/root/*log

