[versions]
kotlinVersion = "1.6.10"
kotlinxSerializationVersion = "1.3.1"
kotlinxDateTime = "0.1.0"
sqlDelight = "1.5.3"
androidGradlePlugin = "7.0.4"
composeJetpackCompiler = "1.1.0-rc02"
composeJetpack = "1.1.0-rc01"
androidComposeActivity = "1.3.0"
androidComposeDesktop = "1.0.1-rc2"
androidFragments = "1.2.5"
androidMaterial = "1.2.1"
androidAppCompat = "1.2.0"
androidConstraintLayout = "2.0.2"
androidCoreKts = "1.2.0"
androidLifecycle = "2.2.0"

mokoResources = "0.17.2"
decomposeVersion = "0.4.0"
essenty = "0.2.2"
coroutines = "1.6.0-native-mt"
ktor = "1.5.4"
okio = "3.0.0"
napier = "1.4.1"
uuid = "0.3.0"
junit = "4.13"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlinVersion" }
kotlinTestAnnotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlinVersion" }
kotlinTestJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinVersion" }
kotlinxSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinVersion" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
kotlinxDateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }

androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidFragments = { module = "androidx.fragment:fragment-ktx", version.ref = "androidFragments" }
androidMaterial = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
androidAppCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompat" }
androidConstraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidConstraintLayout" }
androidCoreKts = { module = "androidx.core:core-ktx", version.ref = "androidCoreKts" }
androidViewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidLifecycle" }
androidLifecycleKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidLifecycle" }
androidComposeCompiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeJetpackCompiler" }
androidComposeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeJetpack" }
androidComposeMaterial = { module = "androidx.compose.material:material", version.ref = "composeJetpack" }
androidComposeActivity = {  module = "androidx.activity:activity-compose", version.ref = "androidComposeActivity" }
androidComposeUITooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeJetpack" }
androidComposeUIToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeJetpack" }
androidComposeDesktop = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "androidComposeDesktop" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decomposeVersion" }
decomposeJetpack = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decomposeVersion" }
decomposeJetbrains = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decomposeVersion" }

essentyParcelable = { module = "com.arkivanov.essenty:parcelable", version.ref = "essenty" }
essentryInstanceKeeper = { module = "com.arkivanov.essenty:instance-keeper", version.ref = "essenty" }
essentryStateKeeper = { module = "com.arkivanov.essenty:state-keeper", version.ref = "essenty" }

uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }

sqlDelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelight" }
sqlDelightRuntime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
sqlDelightiOSDriver = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlDelightAndroidDriver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelightJvmDriver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }

coroutinesCommon = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

ktorCommonCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorAndroidClient = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktoriOSClient = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktorDesktop = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
logger = { module = "com.github.aakira:napier", version.ref = "napier" }
junit = { module = "junit:junit", version.ref = "junit" }

mokoResourcesLib = { module = "dev.icerock.moko:resources", version.ref = "mokoResources"}
mokoResourcesGenerator = { module = "dev.icerock.moko:resources-generator", version.ref = "mokoResources"}