[versions]
kotlinVersion = "1.8.20"
kotlinxSerializationVersion = "1.4.1"
kotlinxDateTime = "0.4.0"
sqlDelight = "1.5.5"
androidGradlePlugin = "8.0.2"

kotlinPoet = "1.14.2"

composeJetpackCompiler = "1.4.7"
composeJetpackUiTooling = "1.3.2"
composeJetpack = "1.4.0"
androidComposeActivity = "1.4.0"
androidComposeDesktop = "1.4.0"
androidFragments = "1.4.1"
androidMaterial = "1.6.1"
androidAppCompat = "1.4.2"
androidConstraintLayout = "2.1.4"
androidCoreKts = "1.8.0"
androidLifecycle = "2.4.1"
dagger = "2.46"
playServicesPlugin = "4.3.13"
playServicesAuth = "20.4.0"

mokoResources = "0.23.0"
decomposeVersion = "0.7.0"
essenty = "0.2.2"
coroutines = "1.6.0-native-mt"
ktor = "2.2.2"
okio = "3.0.0"
napier = "2.6.1"
uuid = "0.3.0"
junit = "4.13"
stately = "1.2.0"
mockitoKotlin = "4.0.0"
settings = "0.9"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlinVersion" }
kotlinTestAnnotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlinVersion" }
kotlinTestJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinVersion" }
kotlinxSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinVersion" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
kotlinxDateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }

kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }

androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidFragments = { module = "androidx.fragment:fragment-ktx", version.ref = "androidFragments" }
androidMaterial = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
androidAppCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompat" }
androidConstraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidConstraintLayout" }
androidCoreKts = { module = "androidx.core:core-ktx", version.ref = "androidCoreKts" }
androidViewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidLifecycle" }
androidLifecycleKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidLifecycle" }
androidComposeCompiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeJetpackCompiler" }
androidComposeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeJetpack" }
androidComposeMaterial = { module = "androidx.compose.material:material", version.ref = "composeJetpack" }
androidComposeActivity = {  module = "androidx.activity:activity-compose", version.ref = "androidComposeActivity" }
androidComposeUITooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeJetpackUiTooling" }
androidComposeUIToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeJetpackUiTooling" }
androidComposeDesktop = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "androidComposeDesktop" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

playServicesPlugin = { module = "com.google.gms:google-services", version.ref = "playServicesPlugin" }
playServicesAuth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decomposeVersion" }
decomposeJetpack = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decomposeVersion" }
decomposeJetbrains = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decomposeVersion" }

essentyParcelable = { module = "com.arkivanov.essenty:parcelable", version.ref = "essenty" }
essentryInstanceKeeper = { module = "com.arkivanov.essenty:instance-keeper", version.ref = "essenty" }
essentryStateKeeper = { module = "com.arkivanov.essenty:state-keeper", version.ref = "essenty" }

uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }

sqlDelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelight" }
sqlDelightRuntime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
sqlDelightiOSDriver = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlDelightAndroidDriver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelightJvmDriver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }

coroutinesCommon = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutinesCommonTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutinesSwing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }

ktorCommonCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorAuth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktorAndroidClient = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktoriOSClient = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktorDesktop = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktorLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorContentEncoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }

statelyCommon = { module = "co.touchlab:stately-common", version.ref = "stately" }
statelyConcurrency = { module = "co.touchlab:stately-concurrency", version.ref = "stately" }

settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
settingsCoroutinesMt = { module = "com.russhwolf:multiplatform-settings-coroutines-native-mt", version.ref = "settings" }
settingsCoroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "settings" }
settingsDataStore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "settings" }

mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okioFakeFileSystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
logger = { module = "io.github.aakira:napier", version.ref = "napier" }
junit = { module = "junit:junit", version.ref = "junit" }

mokoResourcesLib = { module = "dev.icerock.moko:resources", version.ref = "mokoResources"}
mokoResourcesGenerator = { module = "dev.icerock.moko:resources-generator", version.ref = "mokoResources"}
mokoCompose = { module = "dev.icerock.moko:resources-compose", version.ref = "mokoResources"}