{
 "title": "first prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "rootlogs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"rootlogs\"}"
    }
   ]
  },
  {
   "title": "nginx - error.log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"nginx\"} | filename = `/var/log/nginx/error.log`"
    }
   ]
  },
  {
   "title": "nginx - access_log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"nginx\"} | filename = `/var/log/nginx/access_log`"
    }
   ]
  },
  {
   "title": "nginx - access_log - 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{job=\"nginx\"} | status = 200 | filename = `/var/log/nginx/access_log` | json | unwrap request_time [$__interval]) by (request_uri)"
    }
   ]
  },
  { "title": "New Panel", "type": "logs", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 } },
  {
   "title": "nginx - access_log - errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{job=\"nginx\"} | status != 200 | filename = `/var/log/nginx/access_log` | json | unwrap request_time [$__interval]) by (request_uri)"
    }
   ]
  },
  {
   "title": "mongodb_collstats_storageStats_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_size",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "New Panel", "type": "logs", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 } },
  {
   "title": "mongodb_dbstats_dataSize",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "mongodb_dbstats_dataSize", "legendFormat": "{{database}}" }
   ]
  },
  { "title": "New Panel", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 } },
  {
   "title": "New Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "quantile_over_time(\n    0.99,\n    {job=\"dockerlogs\"} \n    | json | unwrap request_time  [$__interval]\n) by (request_uri)"
    }
   ]
  },
  {
   "title": "mongo avg Obj size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mongodb_dbstats_avgObjSize", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "dbstats datasize",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "expr": "mongodb_dbstats_dataSize", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  }
 ]
}