{
 "title": "Services",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "nginx - access_log - 200...299",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n        quantile_over_time(\n            0.95,\n            {service_name=\"nginx\", filename = \"/var/log/nginx/access_log\"} | status >= 200 and status < 300 | json | unwrap request_time [$__auto]\n        ) by (request_uri), \n        \"request_uri\", \n        \"/api/dict/words/*\", \n        \"request_uri\", \n        \"/api/dict/words/.*\"\n    ),\n    \"request_uri\", \n    \"/api/cardsets/search*\", \n    \"request_uri\", \n    \"/api/cardsets/search.*\"\n)"
    }
   ]
  },
  {
   "title": "nginx - access_log - 300..499",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\n    quantile_over_time(\n        0.95,\n        {service_name=\"nginx\"} | status >= 300 and status < 500 | filename = `/var/log/nginx/access_log` | json | unwrap request_time [$__interval]\n    ) by (request_uri), \n    \"request_uri\", \n    \"/api/dict/words/*\", \n    \"request_uri\", \n    \"/api/dict/words/.*\"\n)"
    }
   ]
  },
  {
   "title": "nginx - access_log - 500...",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{service_name=\"nginx\"} | status >= 500 | filename = `/var/log/nginx/access_log` | json | unwrap request_time [$__interval]) by (request_uri)"
    }
   ]
  },
  { "title": "Auth Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "auth service log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (level) (\n    count_over_time(\n        {service_name=\"service_auth\", level=\"INFO\"}[1m]\n    )\n)"
    },
    {
     "expr": "sum by (level) (\n    count_over_time(\n        {service_name=\"service_auth\", level!=\"INFO\"}[1m]\n    )\n)"
    }
   ]
  },
  {
   "title": "auth service log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{service_name=\"service_auth\"}"
    }
   ]
  },
  { "title": "Cardsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "cardsets service log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (level) (\n    count_over_time(\n        {service_name=\"service_cardsets\", level=\"INFO\"}[1m]\n    )\n)"
    },
    {
     "expr": "sum by (level) (\n    count_over_time(\n        {service_name=\"service_cardsets\", level!=\"INFO\"}[1m]\n    )\n)"
    }
   ]
  },
  {
   "title": "cardsets service log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "{service_name=\"service_cardsets\"}"
    }
   ]
  },
  { "title": "Cardsetsearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "cardsetsearch service log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (level) (\n    count_over_time(\n        {service_name=\"service_cardsetsearch\", level=\"INFO\"}[1m]\n    )\n)"
    },
    {
     "expr": "sum by (level) (\n    count_over_time(\n        {service_name=\"service_cardsetsearch\", level!=\"INFO\"}[1m]\n    )\n)"
    }
   ]
  },
  {
   "title": "cardsetsearch service log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "{service_name=\"service_cardsetsearch\"}"
    }
   ]
  },
  { "title": "Dict", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "dict service log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by (level) (\n    count_over_time(\n        {service_name=\"service_dict\", level=\"INFO\"}[1m]\n    )\n)"
    },
    {
     "expr": "sum by (level) (\n    count_over_time(\n        {service_name=\"service_dict\", level!=\"INFO\"}[1m]\n    )\n)"
    }
   ]
  },
  {
   "title": "dict service log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "{service_name=\"service_dict\"}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "rootlogs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "{job=\"rootlogs\"}"
    }
   ]
  },
  {
   "title": "nginx - error.log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "{service_name=\"nginx\"} | filename = `/var/log/nginx/error.log`"
    }
   ]
  },
  {
   "title": "nginx - access_log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "{service_name=\"nginx\"} | filename = `/var/log/nginx/access_log`"
    }
   ]
  },
  { "title": "Mongo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "mongodb_collstats_storageStats_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mongo avg Obj size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mongodb_dbstats_avgObjSize", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "mongodb_dbstats_dataSize",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "targets": [
    { "expr": "mongodb_dbstats_dataSize", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "dbstats datasize",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "targets": [
    { "expr": "mongodb_dbstats_dataSize", "legendFormat": "__auto" }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "go goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go gc duration sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go memstats alloc bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}